server:
  port: ${SERVER_PORT:5081}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://192.168.56.213:8761/eureka}

spring:
  application:
    name: iti-service-auth
  config.import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://192.168.56.213:8888}
